kdgparking/Controllers/CSVController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using kdgparking.BL;
using kdgparking.BL.Domain;

using Microsoft.AspNetCore.Hosting;
using OfficeOpenXml;

namespace kdgparking.Controllers
{
    public class CSVController : Controller
    {
        private IManager mgr = new Manager();

        // GET: CSV
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            // TODO : Add security restrictions
            if (file != null && file.ContentLength > 0)
                try
                {
                    // Send file to BL for processing
                    mgr.ProcessFile(file);
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                }
            else
            {
                ViewBag.Message = "You have not specified a file.";
            }
            return View();
        }
    }
}

kdgparking/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using kdgparking.BL;
using kdgparking.BL.Domain;

namespace kdgparking.Controllers
{
    public class HomeController : Controller
    {
        private IManager mgr = new Manager();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult CRUD()
        {
            ViewBag.Message = "CRUD page";

            return View();
        }
    }
}

kdgparking/Controllers/PersoonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using kdgparking.BL;
using kdgparking.BL.Domain;
using System.Net.Mail;

namespace testParkingWeb.Controllers
{
    public class PersoonController : Controller
    {
        private IManager mng = new Manager();
        public int tmpPhone = 031112233;

        public ActionResult voegPersoonToe(string naam, string voornaam, DateTime start, DateTime end, string email, string company, string nummerplaat)
        {
            Holder nieuweHolder;
            try
            {
                //nieuwePersoon = new Persoon(naam, voornaam, start, end, company, new MailAddress(email), nummerplaat);
                nieuweHolder = mng.AddHolder("UniekeString001", naam, voornaam, tmpPhone, email);
                Console.WriteLine("Created new Person");
            } catch
            {
                Console.WriteLine("Failed to create new Person");
                return new HttpStatusCodeResult(500);
            }
            //mng.AddHolder(nieuwePersoon);
            return new HttpStatusCodeResult(200);
        }

        public ActionResult Toevoegen()
        {
            return View();
        }
    }
}

kdgparking/Views/CSV/Index.cshtml
@{
    ViewBag.Title = "File Uploaden";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h2>Basic File Upload</h2>
    @using (Html.BeginForm("Index",
                            "CSV",
                            FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
    {
        <label for="file">Upload File:</label>
        <input type="file" name="file" id="file" /><br><br>
        <input type="submit" value="Upload File" />
        <br><br>
        @ViewBag.Message
    }
</body>
</html>

kdgparking/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

kdgparking/Views/Home/CRUD.cshtml
@{
    ViewBag.Title = "CRUD";
}

<html>
<body>
    <div class="w3-row-padding w3-center w3-margin-top">
        <div class="w3-first">
            <div class="w3-card w3-container" style="min-height:210px">
                <br>
                <i class="fa fa-desktop w3-margin-bottom w3-text-theme" style="font-size:120px;cursor: pointer;"
                   onclick="window.location.href='@Url.Action("CRUD","Home")"></i>
                <br>
                <h3>CRUD</h3>
            </div>
        </div>
     </div>
</body>
</html>

kdgparking/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

kdgparking/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<!DOCTYPE html>

<html>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<body>
    <div class="w3-row-padding w3-center w3-margin-top">
        <div class="w3-third">
            <div class="w3-card w3-container" style="min-height:210px">
                <br>
                <i class="fa fa-desktop w3-margin-bottom w3-text-theme" style="font-size:120px;cursor: pointer;"
                   onclick="window.location.href='CRUD'"></i>
                <br>
                <h3>CRUD</h3>
            </div>
        </div>
        <div class="w3-third">
            <div class="w3-card w3-container" style="min-height:210px">
                <br>
                <i class="fa fa-camera w3-margin-bottom w3-text-theme" style="font-size:120px;cursor: pointer;"
                   onclick="window.location.href='index.html'"></i>
                <br>
                <h3>Camera</h3>
            </div>
        </div>
        <div class="w3-third">
            <div class="w3-card w3-container" style="min-height:210px">
                <br>
                <i class="fa fa-file-excel-o w3-margin-bottom w3-text-theme" style="font-size:120px;cursor: pointer;"
                   onclick="window.location.href='index.html'"></i>
                <br>
                <h3>CSV Upload</h3>
            </div>
        </div>
    </div>
</body>
</html>

kdgparking/Views/Persoon/Toevoegen.cshtml
@{
    ViewBag.Title = "Persoon Toevoegen";
}
@section Styles {
    <link href="@Url.Content("~/Styles/Toevoegen.css")" rel="stylesheet" type="text/css" />
}
<h2>Persoon Toevoegen</h2>
<div id="persoonForm">
    <form method="post" action="postPersoon">
        <div class="persoonForm">
            <h3 id="verplichtTitel">Verplicht</h3>
            <div class="col1">
                <label for="naamField">Naam</label>
                <input type="text" name="naam" placeholder="Naam" id="naamField" />
                <label for="voornaamField">Voornaam</label>
                <input type="text" name="voornaam" placeholder="Voornaam" id="voornaamField" />
                <label for="emailField">Email</label>
                <input type="email" name="email" placeholder="Email" id="emailField" />
            </div>
            <div class="col2">
                <label for="companyField">Company</label>
                <input type="text" name="company" placeholder="Company" id="companyField" />
                <label for="startdatumField">Startdatum</label>
                <input type="date" name="start" placeholder="Startdatum" id="startdatumField" />
                <label for="einddatumField">Einddatum</label>
                <input type="date" name="end" placeholder="Einddatum" id="einddatumField" />
            </div>
        </div>
        <div class="persoonForm">
            <h3 id="optioneelTitel">Optioneel</h3>
            <label for="nummerplaatField">Nummerplaat</label>
            <input type="text" name="nummerplaat" placeholder="Nummerplaat" id="nummerplaatField"/>
        </div>
        <input type="submit" />
    </form>
</div>

kdgparking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Parking CZ</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("Styles", false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Parking KdG Zuid", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Toevoegen", "Toevoegen", "Persoon")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Karel De Grote Hogeschool - <a href="https://www.kdg.be/gebruiksvoorwaarden-en-privacy">Gebruiksvoorwaarden en privacy</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>